# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.6.1

    working_directory: ~/SixtyPical

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            git clone https://github.com/catseye/Falderal
            git clone https://github.com/catseye/dcc6502
            (cd dcc6502 && make)

      - run:
          name: run tests
          command: |
            PATH=dcc6502:Falderal/bin:$PATH ./test.sh
